spring:
  application:
    name: tutorial12
  datasource:
    url: jdbc:h2:file:./tutorial12/data/data
    username: TPO
    password: TPO_Lecture
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
  banner:
    location: logo-app

