spring:
  application:
    name: tutorial11
  banner:
    location: logo-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./tutorial11/data/data
    username: sa
    password: